### ISSUE TITLE
Вимоги

### ISSUE THREAD

**Issue by pasharik95** [VadyaVL/CoinsDiffusion#14]
1. Програма повинна вірно вирішувати завдання : моделювання поширення монет євро по всій Європі.
2. Програма повина отримувати початкові дані з вхідного файлу.
3. Вхідний файл повинен бути у такому форматі:
n
Country_1 xl_1 yl_1 xh_1 yh_1
...
County_n xl_n yl_n xh_n yh_n 

Де n - кількість країн. xl, yl, xh, yh - координати країни.
4. Програма повинна забезпити можливість вирішення задачі для багатьох випадків, які будуть записані в одному файлі.
5. Завершення моделювання - ситуація при якій у кожному місті є монета кожного вхідного зразку.
6. Програма повинна записувати результат у вихідний файл.
7. Файл повиний бути у такому форматі:
Номер_випадку
Назва_країни кількість_днів_для_завершення

**Comment by VadyaVL** [comment]
Please. Remove or close it.
